config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/cats")

  resources :cats, only: [:create, :index, :show, :new, :edit, :update]
  resources :cat_rental_requests, only: [:new, :create] do
    member do 
      post 'approve'
      post 'deny'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  include ActionView::Helpers::DateHelper

  COLORS = %w(black tabby white blue chocolate cinnamon lilac lavender red sable brown cream).freeze

  validates :birth_date, presence: true
  validates :color, presence: true, inclusion: COLORS
  validates :name, presence: true, uniqueness: true
  validates :sex, presence: true, inclusion: %w(M F)
  validates :description, presence: true

  has_many :rental_requests,
    class_name: 'CatRentalRequest',
    dependent: :destroy

  def age
    time_ago_in_words(birth_date)
  end 
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :does_not_overlap_approved_request

  belongs_to :cat
  def approve!
    transaction do
      self.status = "APPROVED"
      self.save!

      overlapping_pending_requests.each do |request|
        request.deny!
      end
    end
  end

  def deny!
    self.status = "DENIED"
    self.save!
  end

  def pending?
    self.status == "PENDING"
  end

  private

  def overlapping_requests
    CatRentalRequest
      .where.not(id: id)
      .where(cat_id: cat_id)
      .where.not('start_date > :end_date OR end_date < :start_date', start_date: start_date, end_date: end_date)
  end

  def overlapping_approved_requests
    overlapping_requests.where(status: "APPROVED")
  end

  def overlapping_pending_requests
    overlapping_requests.where(status: "PENDING")
  end

  def does_not_overlap_approved_request
    unless overlapping_approved_requests.empty?
      errors[:base] << "Request overlaps with an approved request"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cats = Cat.all
    @rental_request = CatRentalRequest.new
    render :new
  end

  def create
    @cats = Cat.all
    @rental_request = CatRentalRequest.new(rental_params)
    if @rental_request.save
      redirect_to cat_url(@rental_request.cat)
    else
      render :new
    end
  end

  def approve
    rental_request = CatRentalRequest.find_by(id: params[:id])
    rental_request.approve!
  end
  
  def deny
    rental_request = CatRentalRequest.find_by(id: params[:id])
    rental_request.deny!
  end

  private
  def rental_params
    params.require(:rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    @rentals = @cat.rental_requests.order(:start_date)
    
    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end
  end

  def update
    @cat = Cat.find_by(id: params[:id])
    @cat.update(cat_params)
    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :sex, :birth_date, :color, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cat_rental_requests/new.html.erb
<% cats = @cats %>
<h2>Rent a Cat</h2>

<form action="<%= cat_rental_requests_url %>" method="POST">
  <select name="rental_request[cat_id]">
    <option disabled selected>Choose a cat</option>
    <% cats.each do |cat| %>
    <% selected = @rental_request.cat_id == cat.id %>
      <option 
      value="<%=cat.id%>"
      <%= selected ? "selected" : "" %>
      >
        <%= cat.name %>
      </option>
    <% end %>
  </select>

  <br>
  <br>
  <label for="start-date">Start date:</label>
  <input id="start-date" type="date" name="rental_request[start_date]">

  <br>
  <br>
  <label for="end-date">End date:</label>
  <input id="end-date" type="date" name="rental_request[end_date]">

  <br>
  <input type="submit" value="Submit Rental Request">
</form>

app/views/cats/_form.html.erb
<% action_url = cat.persisted? ? cat_url(cat) : cats_url %>

<h2>Edit A Cat!<h2>
<form action="<%= action_url %>" method="POST">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>

  <label for="name">Name</label>
  <input id="name" type="text" name="cat[name]" value="<%= cat.name %>">
  
  <label for="male">Male</label>
  <input id="male" type="radio" name="cat[sex]" value="M" <%= (cat.sex == "M") ? "checked" : "" %> >
  <label for="male">Female</label>
  <input id="male" type="radio" name="cat[sex]" value="F" <%= (cat.sex == "F") ? "checked" : "" %> >
  
  <br>
  <br>
  <label for="color">Color</label>
  <select id="color" name="cat[color]">
    <option selected disabled>-- Select a color --</option>
    <% Cat::COLORS.each do |color| %>
      <option value="<%=color%>" <%= (cat.color == color) ? "selected" : "" %>><%= color %></option>
    <% end %>
  </select>

  <label for="bday">Birthday:</label>
  <input id="bday" type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">

  <br>
  <br>
  <label for="desc">Description</label>
  <textarea id="desc" name="cat[description]" rows="5" cols="33" style="resize:none"><%= cat.description %></textarea>

  <br>
  <% submit_text = cat.persisted? ? "Update Cat!" : "Create Cat!"  %>
  <input type="submit" value="<%=submit_text%>">
</form>

app/views/cats/edit.html.erb
<%= render 'form', cat: @cat %>

app/views/cats/index.html.erb
<h2>All the Cats</h2>
<% @cats.each do |cat| %>
  <%= link_to "#{cat.name}", cat_url(cat)%><br>
<% end %>

app/views/cats/new.html.erb
<%= render 'form', cat: @cat %>

app/views/cats/show.html.erb
<% cat = @cat %>
<% rentals = @rentals %>

<h2 style="text-align: center"><%= cat.name %></h2>
  <table>
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>

    <tr>
      <td>Age</td>
      <td><%= cat.age %></td>
    </tr>

    <tr>
      <td>Birth Date</td>
      <td><%= cat.birth_date %></td>
    </tr>

    <tr>
      <td>Color</td>
      <td><%= cat.color %></td>
    </tr>

    <tr>
      <td>Sex</td>
      <td><%= cat.sex %></td>
    </tr>
  </table>

  <h3>Rentals</h3>
  <table>
    <tr>
      <th>Start date</th>
      <th>End date</th>
      <th>Status</th>
    </tr>
    <% rentals.each do |rental| %>
      <tr>
        <td><%= rental.start_date  %></td>
        <td><%= rental.end_date  %></td>
        <td>
          <% if rental.pending? %>
            <%= button_to 'Approve Request', approve_cat_rental_request_url(rental), method: :post %>
            <%= button_to 'Deny Request', deny_cat_rental_request_url(rental), method: :post %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%="99 Cats"%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <h1 style="text-align: center">99 Cats</h1>
    <%= yield %>
  </body>
</html>